### PR TITLE
running on ios and instructions

### PR DESCRIPTION
**Pull request by makedirectory**
Hello!

I've got everything running on iOS and added some instructions.
Screen Shot 2019-11-13 at 11 50 56 PM

### CODE REVIEW

**Comment by wendelfreitas** [comment]
@makedirectory thanks for the pr, i will look at your branch and as soon as i can i accept the merge :hearts:

**Comment by makedirectory** [comment]
> @makedirectory thanks for the pr, i will look at your branch and as soon as i can i accept the merge ♥️

Let me know if you have any questions. Next up... update to RN .61. Also would be extremely helpful of you could add a strings file for translations because I can't read the alerts :)

**Comment by renanmav** [comment]
Works fine for me, but we could fix the header size too.

image

**Comment by makedirectory** [comment]
> Works fine for me, but we could fix the header size too.

Hey @renanmav! We should make a list of items to tackle for iOS, I also noticed a few other things that could get taken care of like one signal is not completely setup (I believe - didn't explore extensively). 

Interested?

Cheers,
Andrew

**Comment by renanmav** [comment]
Sure

**Pull request merged**
